# Generated by Django 5.2.14 on 2026-06-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0007_teamtournamentstatus_mathematically_eliminated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('api_football', 'API-Football')], default='api_football', max_length=40)),
                ('provider_fixture_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('halftime', 'Half-time'), ('extra_time', 'Extra time'), ('penalties', 'Penalties'), ('final', 'Final'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('suspended', 'Suspended'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('provider_state_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_state_code', models.CharField(blank=True, max_length=60)),
                ('provider_state_name', models.CharField(blank=True, max_length=120)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('went_to_extra_time', models.BooleanField(default=False)),
                ('went_to_penalties', models.BooleanField(default=False)),
                ('penalty_home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalty_away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='tournaments.match')),
            ],
            options={
                'ordering': ['match__kickoff_time', 'match__match_number', 'match_id'],
                'indexes': [models.Index(fields=['provider', 'provider_fixture_id'], name='live_scores_provide_c9506f_idx'), models.Index(fields=['status'], name='live_scores_status_f6ed48_idx'), models.Index(fields=['last_seen_at'], name='live_scores_last_se_b9d051_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderFixtureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('api_football', 'API-Football')], default='api_football', max_length=40)),
                ('provider_fixture_id', models.CharField(max_length=80)),
                ('provider_league_id', models.CharField(blank=True, max_length=80)),
                ('provider_season_id', models.CharField(blank=True, max_length=80)),
                ('provider_home_name', models.CharField(blank=True, max_length=160)),
                ('provider_away_name', models.CharField(blank=True, max_length=160)),
                ('provider_starting_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='tournaments.match')),
            ],
            options={
                'ordering': ['provider', 'provider_starting_at', 'provider_fixture_id'],
                'indexes': [models.Index(fields=['provider', 'provider_fixture_id'], name='live_scores_provide_61f95f_idx'), models.Index(fields=['provider_starting_at'], name='live_scores_provide_dd205a_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_fixture_id'), name='unique_provider_fixture'), models.UniqueConstraint(fields=('provider', 'match'), name='unique_provider_match_mapping')],
            },
        ),
    ]
