# Generated by Django 5.2.14 on 2026-05-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.PositiveIntegerField()),
                ('host', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('complete', 'Complete')], default='upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fifa_code', models.CharField(max_length=3)),
                ('confederation', models.CharField(blank=True, max_length=20)),
                ('pot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fifa_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['pot', 'name'],
                'unique_together': {('tournament', 'fifa_code')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarterfinal', 'Quarterfinal'), ('semifinal', 'Semifinal'), ('third_place', 'Third-place Match'), ('final', 'Final')], max_length=30)),
                ('kickoff_time', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('went_to_extra_time', models.BooleanField(default=False)),
                ('went_to_penalties', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='tournaments.nationalteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='tournaments.nationalteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='tournaments.nationalteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['kickoff_time', 'id'],
            },
        ),
    ]
