# Generated by Django 5.2.14 on 2026-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalteam',
            name='flag',
            field=models.CharField(blank=True, default='🏳️', max_length=8),
        ),
    ]
