# Generated by Django 5.2.14 on 2026-05-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTournamentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_from_group', models.BooleanField(default=False)),
                ('eliminated_stage', models.CharField(blank=True, choices=[('group', 'Group Stage'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarterfinal', 'Quarterfinal'), ('semifinal', 'Semifinal'), ('third_place', 'Third-place Match'), ('final', 'Final'), ('champion', 'Champion')], max_length=30)),
                ('finish_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_status', to='tournaments.nationalteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statuses', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['finish_rank', 'team__name'],
            },
        ),
    ]
