# Generated by Django 5.2.14 on 2026-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_nationalteam_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalteam',
            options={'ordering': ['group', 'pot', 'name']},
        ),
        migrations.AddField(
            model_name='nationalteam',
            name='iso2_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='nationalteam',
            name='flag',
            field=models.CharField(blank=True, default='🏳️', max_length=16),
        ),
    ]
