# Generated by Django 5.2.14 on 2026-05-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_nationalteam_options_nationalteam_iso2_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['kickoff_time', 'match_number', 'id']},
        ),
        migrations.AddField(
            model_name='match',
            name='away_slot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='match',
            name='home_slot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='tournaments.nationalteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='tournaments.nationalteam'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'match_number')},
        ),
    ]
