# Generated by Django 5.2.14 on 2026-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_match_options_match_away_slot_match_home_slot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date', 'kickoff_time', 'match_number', 'id']},
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
