# Generated by Django 5.2.14 on 2026-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_match_options_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
