# Generated by Django 5.2.14 on 2026-05-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtournamentstatus',
            name='mathematically_eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamtournamentstatus',
            name='mathematically_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
