from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from functools import reduce
from itertools import product
from operator import mul
import re
import time
from typing import Callable, Iterable

from django.db import transaction
from django.utils import timezone

from leagues.models import League, LeagueMember
from scoring.defaults import default_scoring_config
from scoring.models import ProjectionEntry, StandingEntry
from tournaments.bracket_nodes import BracketInputNode, build_bracket_graph
from tournaments.mathematical_status import _compute_group_outcome_envelope
from tournaments.models import Match, NationalTeam, TeamTournamentStatus
from tournaments.qualification import compute_qualification
from tournaments.third_place import load_fifa_third_place_table


DIRECT_SLOT_RE = re.compile(r"^[12][A-L]$")
THIRD_PLACEHOLDER_RE = re.compile(r"^3[A-L]+$")
WINNER_SLOT_RE = re.compile(r"^W(\d+)$")
LOSER_SLOT_RE = re.compile(r"^L(\d+)$")


@dataclass(frozen=True)
class ManagerMaxPointsProjection:
    """Maximum reachable fantasy score for one league member."""

    member: LeagueMember
    current_points: Decimal
    max_possible_points: Decimal
    remaining_possible_points: Decimal
    best_case_slots: dict[int, str | None]


@dataclass(frozen=True)
class TeamProjectionOption:
    """Fantasy-distinct future option for one national team.

    This is intentionally compact.  It represents bracket-relevant outcomes
    rather than every raw group-result scenario that can produce them.
    """

    team_id: int
    source_position: int | None
    source_slot: str | None
    bracket_node_id: str | None
    display_slot: str | None
    qualified: bool
    qualification_bonus: Decimal
    group_future_points: Decimal
    third_group: str | None = None

    @property
    def is_third_place_option(self) -> bool:
        return self.source_position == 3 and self.third_group is not None


@dataclass(frozen=True)
class KnockoutPointComponent:
    """One fantasy scoring component generated by a knockout match."""

    team_id: int
    label: str
    points: Decimal


@dataclass(frozen=True)
class KnockoutPathEvent:
    """One selected match outcome in the best future knockout path."""

    match_number: int | None
    stage: str
    home_team_id: int | None
    away_team_id: int | None
    winner_team_id: int | None
    loser_team_id: int | None
    components: tuple[KnockoutPointComponent, ...]

    @property
    def points(self) -> Decimal:
        return sum((component.points for component in self.components), Decimal("0"))


@dataclass(frozen=True)
class KnockoutSearchResult:
    """Best knockout score plus the selected path that produced it."""

    points: Decimal
    events: tuple[KnockoutPathEvent, ...]


Logger = Callable[[str], None]


class _ProjectionLogger:
    def __init__(self, *, enabled: bool):
        self.enabled = enabled
        self.started_at = time.monotonic()

    def __call__(self, message: str) -> None:
        if not self.enabled:
            return
        elapsed = time.monotonic() - self.started_at
        print(f"[projections +{elapsed:8.1f}s] {message}", flush=True)


def get_projection_entries_by_member_id(
    league: League,
) -> dict[int, ProjectionEntry]:
    """Return cached max-points projections keyed by league member id."""
    return {
        entry.member_id: entry
        for entry in ProjectionEntry.objects.filter(league=league).select_related("member")
    }


def mark_projection_entries_stale(
    league: League,
    *,
    reason: str = "Tournament state changed.",
) -> None:
    """Mark cached projections stale without recalculating them."""
    ProjectionEntry.objects.filter(league=league).update(
        is_stale=True,
        stale_reason=reason[:160],
    )


def ensure_projection_entries_exist(
    league: League,
    *,
    reason: str = "Projection has not been calculated yet.",
) -> None:
    """Create stale placeholder projection rows for current league members."""
    existing_member_ids = set(
        ProjectionEntry.objects.filter(league=league).values_list("member_id", flat=True)
    )

    placeholders = []

    for member in league.members.all():
        if member.id in existing_member_ids:
            continue

        placeholders.append(
            ProjectionEntry(
                league=league,
                member=member,
                is_stale=True,
                stale_reason=reason,
            )
        )

    if placeholders:
        ProjectionEntry.objects.bulk_create(placeholders, ignore_conflicts=True)


def recompute_projection_entries(
    league: League,
    *,
    verbose: bool = True,
) -> dict[int, ProjectionEntry]:
    """Recompute and cache max-points projections for every league member.

    This implementation uses compact team future options derived from the
    tournament mathematical-status layer and bracket-node graph.  It avoids the
    previous brute-force product of every raw group-result scenario.
    """
    logger = _ProjectionLogger(enabled=verbose)
    logger(f"Starting projection recomputation for league={league.slug!r}.")

    projections = compute_league_max_points_projections(
        league,
        verbose=verbose,
        logger=logger,
    )
    now = timezone.now()

    with transaction.atomic():
        current_member_ids = set(league.members.values_list("id", flat=True))
        ProjectionEntry.objects.filter(league=league).exclude(
            member_id__in=current_member_ids
        ).delete()

        for projection in projections.values():
            ProjectionEntry.objects.update_or_create(
                league=league,
                member=projection.member,
                defaults={
                    "current_points": projection.current_points,
                    "max_possible_points": projection.max_possible_points,
                    "remaining_possible_points": projection.remaining_possible_points,
                    "best_case_slots": {
                        str(team_id): slot
                        for team_id, slot in projection.best_case_slots.items()
                    },
                    "is_stale": False,
                    "stale_reason": "",
                    "computed_at": now,
                },
            )

    logger(
        f"Cached {len(projections)} projection rows for league={league.slug!r}."
    )

    return get_projection_entries_by_member_id(league)


def compute_league_max_points_projections(
    league: League,
    *,
    verbose: bool = True,
    logger: Logger | None = None,
) -> dict[int, ManagerMaxPointsProjection]:
    """Compute maximum reachable score for every league member."""
    logger = logger or _ProjectionLogger(enabled=verbose)

    standings_by_member_id = {
        entry.member_id: entry
        for entry in StandingEntry.objects.filter(league=league).select_related("member")
    }

    context = _ProjectionContext(league=league, logger=logger)
    members = list(league.members.all().order_by("display_name", "id"))
    logger(f"Members to compute: {len(members)}.")

    projections: dict[int, ManagerMaxPointsProjection] = {}

    for index, member in enumerate(members, start=1):
        logger(f"Computing member {index}/{len(members)}: {member.display_name}.")
        projections[member.id] = compute_member_max_points_projection(
            league=league,
            member=member,
            standing_entry=standings_by_member_id.get(member.id),
            context=context,
            logger=logger,
        )

    return projections


def compute_member_max_points_projection(
    *,
    league: League,
    member: LeagueMember,
    standing_entry: StandingEntry | None = None,
    context: "_ProjectionContext | None" = None,
    logger: Logger | None = None,
) -> ManagerMaxPointsProjection:
    """Compute the maximum reachable total for one manager."""
    logger = logger or _ProjectionLogger(enabled=False)
    context = context or _ProjectionContext(league=league, logger=logger)

    current_points = (
        Decimal(standing_entry.points)
        if standing_entry is not None
        else Decimal("0")
    )

    teams = list(
        NationalTeam.objects.filter(
            fantasy_assignments__league=league,
            fantasy_assignments__member=member,
        ).order_by("group", "name")
    )

    if not teams:
        return ManagerMaxPointsProjection(
            member=member,
            current_points=current_points,
            max_possible_points=current_points,
            remaining_possible_points=Decimal("0"),
            best_case_slots={},
        )

    logger(
        "  Teams: "
        + ", ".join(f"{team.name} ({team.group or '-'})" for team in teams)
    )

    option_groups = [context.options_for_team(team) for team in teams]
    option_group_sizes = [len(group) for group in option_groups]
    product_size = _product_size(option_group_sizes)
    logger(f"  Option group sizes: {option_group_sizes}; products={product_size:,}.")

    best_remaining = Decimal("0")
    best_slots: dict[int, str | None] = {team.id: None for team in teams}
    best_combo: tuple[TeamProjectionOption, ...] | None = None
    best_group_points = Decimal("0")
    best_qualification_points = Decimal("0")
    best_knockout_points = Decimal("0")
    best_knockout_result = KnockoutSearchResult(points=Decimal("0"), events=())

    for option_index, option_combo in enumerate(product(*option_groups), start=1):
        if option_index == 1 or option_index % 1000 == 0:
            logger(
                f"    Processed {option_index:,}/{product_size:,} option products; "
                f"best remaining={best_remaining}."
            )

        group_points = sum(
            (option.group_future_points for option in option_combo),
            Decimal("0"),
        )

        if not any(option.qualified for option in option_combo):
            # Group points still matter even if nobody qualifies.
            remaining = group_points
            if remaining > best_remaining:
                best_remaining = remaining
                best_slots = {option.team_id: None for option in option_combo}
                best_combo = option_combo
                best_group_points = group_points
                best_qualification_points = Decimal("0")
                best_knockout_points = Decimal("0")
                best_knockout_result = KnockoutSearchResult(points=Decimal("0"), events=())
            continue

        if not context.option_combo_is_valid(option_combo):
            continue

        qualification_points = sum(
            (option.qualification_bonus for option in option_combo),
            Decimal("0"),
        )
        knockout_result = context.max_future_knockout_result(option_combo)
        knockout_points = knockout_result.points
        remaining = group_points + qualification_points + knockout_points

        if remaining > best_remaining:
            best_remaining = remaining
            best_slots = {
                option.team_id: option.display_slot
                for option in option_combo
            }
            best_combo = option_combo
            best_group_points = group_points
            best_qualification_points = qualification_points
            best_knockout_points = knockout_points
            best_knockout_result = knockout_result

    logger(
        f"  Best breakdown for {member.display_name}: "
        f"group={best_group_points}, "
        f"qualification={best_qualification_points}, "
        f"knockout={best_knockout_points}, "
        f"remaining={best_remaining}."
    )
    if best_combo is not None:
        logger("  Best option combo:")
        team_by_id = {team.id: team for team in teams}
        for option in best_combo:
            team = team_by_id.get(option.team_id)
            team_name = team.name if team is not None else f"team_id={option.team_id}"
            logger(
                "    "
                f"{team_name}: "
                f"position={_display_position(option.source_position, option.qualified)}, "
                f"source_slot={option.source_slot or '-'}, "
                f"node={option.display_slot or '-'} "
                f"({option.bracket_node_id or '-'}), "
                f"group_points={option.group_future_points}, "
                f"qualification={option.qualification_bonus}"
            )

    if best_knockout_result.events:
        logger("  Best knockout path:")
        team_by_id = {team.id: team for team in teams}
        for event in best_knockout_result.events:
            logger(_format_knockout_event(event, team_by_id))
            for component in event.components:
                component_team = team_by_id.get(component.team_id)
                component_name = (
                    component_team.name
                    if component_team is not None
                    else f"team_id={component.team_id}"
                )
                logger(
                    "      "
                    f"{component_name}: {component.label} +{component.points}"
                )

    logger(
        f"  Done {member.display_name}: current={current_points}, "
        f"remaining={best_remaining}, max={current_points + best_remaining}."
    )

    return ManagerMaxPointsProjection(
        member=member,
        current_points=current_points,
        max_possible_points=current_points + best_remaining,
        remaining_possible_points=best_remaining,
        best_case_slots=best_slots,
    )


class _ProjectionContext:
    def __init__(self, *, league: League, logger: Logger | None = None):
        self.league = league
        self.tournament = league.tournament
        self.config = default_scoring_config() | league.scoring_config
        self.logger = logger or _ProjectionLogger(enabled=False)
        self.group_envelopes = {
            group: _compute_group_outcome_envelope(self.tournament, group)
            for group in _groups_for_tournament(self.tournament)
        }
        self.bracket_graph = build_bracket_graph(self.tournament)
        self.fifa_table = _load_fifa_table_or_none()
        self.knockout_matches = list(
            Match.objects.filter(tournament=self.tournament)
            .exclude(stage=Match.Stage.GROUP)
            .select_related("home_team", "away_team", "winner")
            .order_by("match_number")
        )
        self.third_slots_by_opponent = _third_slots_by_opponent(self.knockout_matches)
        self.actual_node_by_team = _actual_bracket_node_by_team(
            self.tournament,
            self.bracket_graph.nodes,
        )
        self.group_stage_complete = _all_group_matches_complete(self.tournament)
        self.actual_slot_by_team = _actual_knockout_slot_by_team(
            tournament=self.tournament,
            group_stage_complete=self.group_stage_complete,
            third_slots_by_opponent=self.third_slots_by_opponent,
            fifa_table=self.fifa_table,
        )

    def options_for_team(self, team: NationalTeam) -> list[TeamProjectionOption]:
        """Return compact reachable fantasy outcomes for one team."""
        if _team_is_eliminated_from_future(team):
            return [self._eliminated_option(team)]

        actual_node = self.actual_node_by_team.get(team.id)
        if actual_node is not None:
            return [self._node_option(team=team, node=actual_node, source_position=None)]

        if self.group_stage_complete:
            actual_slot = self.actual_slot_by_team.get(team.id)
            if actual_slot:
                node = self._node_for_source_slot(actual_slot)
                if node is not None:
                    return [self._node_option(team=team, node=node, source_position=None)]
            return [self._eliminated_option(team)]

        envelope = self._team_envelope(team)
        if envelope is None:
            return self._early_default_options(team)

        options: list[TeamProjectionOption] = []
        possible_positions = set(envelope.possible_positions)

        if 1 in possible_positions:
            node = self.bracket_graph.node_for_direct_slot(f"1{team.group}")
            if node is not None:
                options.append(self._node_option(team=team, node=node, source_position=1))

        if 2 in possible_positions:
            node = self.bracket_graph.node_for_direct_slot(f"2{team.group}")
            if node is not None:
                options.append(self._node_option(team=team, node=node, source_position=2))

        if 3 in possible_positions and self._third_place_can_still_qualify(team, envelope):
            for node in self.bracket_graph.possible_nodes_for_third_group(team.group):
                options.append(self._node_option(team=team, node=node, source_position=3))

        if self._elimination_is_possible(possible_positions):
            options.append(self._eliminated_option(team))

        return _dedupe_options(options) or [self._eliminated_option(team)]

    def option_combo_is_valid(
        self,
        option_combo: tuple[TeamProjectionOption, ...],
    ) -> bool:
        """Return whether a concrete bracket option product is feasible enough."""
        node_ids = [option.bracket_node_id for option in option_combo if option.bracket_node_id]
        if len(node_ids) != len(set(node_ids)):
            return False

        source_slots = [option.source_slot for option in option_combo if option.source_slot]
        if len(source_slots) != len(set(source_slots)):
            return False

        return self._third_place_combo_is_fifa_valid(option_combo)

    def max_future_knockout_points(
        self,
        option_combo: tuple[TeamProjectionOption, ...],
    ) -> Decimal:
        """Return only the points for the best future knockout path."""
        return self.max_future_knockout_result(option_combo).points

    def max_future_knockout_result(
        self,
        option_combo: tuple[TeamProjectionOption, ...],
    ) -> KnockoutSearchResult:
        """Return the best future knockout path for this option combo."""
        owned_team_ids = {option.team_id for option in option_combo}
        source_slot_to_team = {
            option.source_slot: option.team_id
            for option in option_combo
            if option.qualified and option.source_slot
        }
        return self._search_knockout_result(
            match_index=0,
            source_slot_to_team=source_slot_to_team,
            owned_team_ids=owned_team_ids,
            winners={},
            losers={},
            points=Decimal("0"),
            events=(),
        )

    def _search_knockout_result(
        self,
        *,
        match_index: int,
        source_slot_to_team: dict[str, int],
        owned_team_ids: set[int],
        winners: dict[int, int | None],
        losers: dict[int, int | None],
        points: Decimal,
        events: tuple[KnockoutPathEvent, ...],
    ) -> KnockoutSearchResult:
        if match_index >= len(self.knockout_matches):
            return KnockoutSearchResult(points=points, events=events)

        match = self.knockout_matches[match_index]
        match_number = match.match_number

        home = self._resolve_participant(
            match=match,
            side="home",
            source_slot_to_team=source_slot_to_team,
            owned_team_ids=owned_team_ids,
            winners=winners,
            losers=losers,
        )
        away = self._resolve_participant(
            match=match,
            side="away",
            source_slot_to_team=source_slot_to_team,
            owned_team_ids=owned_team_ids,
            winners=winners,
            losers=losers,
        )

        if match.is_complete:
            winner = _owned_or_none(match.winner_id, owned_team_ids)
            loser = _owned_or_none(_actual_loser_id(match), owned_team_ids)
            next_winners = dict(winners)
            next_losers = dict(losers)

            if match_number is not None:
                next_winners[match_number] = winner
                next_losers[match_number] = loser

            return self._search_knockout_result(
                match_index=match_index + 1,
                source_slot_to_team=source_slot_to_team,
                owned_team_ids=owned_team_ids,
                winners=next_winners,
                losers=next_losers,
                points=points,
                events=events,
            )

        best = KnockoutSearchResult(points=points, events=events)

        for winner, loser in _winner_loser_branches(home, away):
            components = self._future_match_point_components(
                match=match,
                winner=winner,
                loser=loser,
            )
            match_points = sum(
                (component.points for component in components),
                Decimal("0"),
            )
            next_events = events

            if components:
                next_events = events + (
                    KnockoutPathEvent(
                        match_number=match_number,
                        stage=str(match.stage),
                        home_team_id=home,
                        away_team_id=away,
                        winner_team_id=winner,
                        loser_team_id=loser,
                        components=components,
                    ),
                )

            next_winners = dict(winners)
            next_losers = dict(losers)

            if match_number is not None:
                next_winners[match_number] = winner
                next_losers[match_number] = loser

            candidate = self._search_knockout_result(
                match_index=match_index + 1,
                source_slot_to_team=source_slot_to_team,
                owned_team_ids=owned_team_ids,
                winners=next_winners,
                losers=next_losers,
                points=points + match_points,
                events=next_events,
            )

            if candidate.points > best.points:
                best = candidate

        return best

    def _resolve_participant(
        self,
        *,
        match: Match,
        side: str,
        source_slot_to_team: dict[str, int],
        owned_team_ids: set[int],
        winners: dict[int, int | None],
        losers: dict[int, int | None],
    ) -> int | None:
        actual_team_id = match.home_team_id if side == "home" else match.away_team_id

        if actual_team_id:
            return _owned_or_none(actual_team_id, owned_team_ids)

        slot = (match.home_slot if side == "home" else match.away_slot) or ""
        slot = slot.strip()

        if DIRECT_SLOT_RE.match(slot) or THIRD_PLACEHOLDER_RE.match(slot):
            return _owned_or_none(source_slot_to_team.get(slot), owned_team_ids)

        winner_match = WINNER_SLOT_RE.match(slot)
        if winner_match:
            return winners.get(int(winner_match.group(1)))

        loser_match = LOSER_SLOT_RE.match(slot)
        if loser_match:
            return losers.get(int(loser_match.group(1)))

        return None

    def _future_match_points(
        self,
        *,
        match: Match,
        winner: int | None,
        loser: int | None,
    ) -> Decimal:
        """Return total future fantasy points awarded by one knockout match."""
        return sum(
            (component.points for component in self._future_match_point_components(
                match=match,
                winner=winner,
                loser=loser,
            )),
            Decimal("0"),
        )

    def _future_match_point_components(
        self,
        *,
        match: Match,
        winner: int | None,
        loser: int | None,
    ) -> tuple[KnockoutPointComponent, ...]:
        """Return point components generated by one future knockout match."""
        components: list[KnockoutPointComponent] = []

        if winner is not None:
            components.append(
                KnockoutPointComponent(
                    team_id=winner,
                    label="knockout win",
                    points=Decimal(str(self.config["knockout_win_regulation"])),
                )
            )

        if match.stage == Match.Stage.FINAL:
            if winner is not None:
                components.append(
                    KnockoutPointComponent(
                        team_id=winner,
                        label="champion bonus",
                        points=Decimal(str(self.config["champion_bonus"])),
                    )
                )
            if loser is not None:
                components.append(
                    KnockoutPointComponent(
                        team_id=loser,
                        label="runner-up bonus",
                        points=Decimal(str(self.config["runner_up_bonus"])),
                    )
                )

        elif match.stage == Match.Stage.THIRD_PLACE:
            if winner is not None:
                components.append(
                    KnockoutPointComponent(
                        team_id=winner,
                        label="third-place bonus",
                        points=Decimal(str(self.config["third_place_bonus"])),
                    )
                )
            if loser is not None:
                components.append(
                    KnockoutPointComponent(
                        team_id=loser,
                        label="fourth-place bonus",
                        points=Decimal(str(self.config["fourth_place_bonus"])),
                    )
                )

        return tuple(components)

    def _node_option(
        self,
        *,
        team: NationalTeam,
        node: BracketInputNode,
        source_position: int | None,
    ) -> TeamProjectionOption:
        return TeamProjectionOption(
            team_id=team.id,
            source_position=source_position,
            source_slot=node.source_slot,
            bracket_node_id=node.node_id,
            display_slot=node.display_label,
            qualified=True,
            qualification_bonus=self._future_qualification_bonus(team),
            group_future_points=self._best_group_points_for_position(team, source_position),
            third_group=team.group if source_position == 3 else None,
        )

    def _eliminated_option(self, team: NationalTeam) -> TeamProjectionOption:
        return TeamProjectionOption(
            team_id=team.id,
            source_position=None,
            source_slot=None,
            bracket_node_id=None,
            display_slot=None,
            qualified=False,
            qualification_bonus=Decimal("0"),
            group_future_points=self._best_group_points_for_elimination(team),
            third_group=None,
        )

    def _early_default_options(self, team: NationalTeam) -> list[TeamProjectionOption]:
        options: list[TeamProjectionOption] = []

        for position in (1, 2):
            node = self.bracket_graph.node_for_direct_slot(f"{position}{team.group}")
            if node is not None:
                options.append(self._node_option(team=team, node=node, source_position=position))

        for node in self.bracket_graph.possible_nodes_for_third_group(team.group):
            options.append(self._node_option(team=team, node=node, source_position=3))

        options.append(self._eliminated_option(team))
        return _dedupe_options(options)

    def _team_envelope(self, team: NationalTeam):
        if not team.group:
            return None
        group_envelope = self.group_envelopes.get(team.group)
        if group_envelope is None:
            return None
        return group_envelope.team_outcomes.get(team.id)

    def _best_group_points_for_position(
        self,
        team: NationalTeam,
        position: int | None,
    ) -> Decimal:
        if position is None:
            return Decimal("0")

        envelope = self._team_envelope(team)
        if envelope is not None:
            value = _best_group_fantasy_points_from_position_envelope(
                envelope,
                position=position,
                config=self.config,
            )
            if value is not None:
                return value

        # Safe optimistic fallback for older mathematical_status.py versions.
        return self._max_remaining_group_wins(team)

    def _best_group_points_for_elimination(self, team: NationalTeam) -> Decimal:
        envelope = self._team_envelope(team)
        candidates: list[Decimal] = []

        if envelope is not None:
            for position in (3, 4):
                value = _best_group_fantasy_points_from_position_envelope(
                    envelope,
                    position=position,
                    config=self.config,
                )
                if value is not None:
                    candidates.append(value)

        if candidates:
            return max(candidates)

        return self._max_remaining_group_wins(team)

    def _max_remaining_group_wins(self, team: NationalTeam) -> Decimal:
        remaining_matches = Match.objects.filter(
            tournament=self.tournament,
            stage=Match.Stage.GROUP,
            status__in=[Match.Status.SCHEDULED, Match.Status.LIVE],
        ).filter(
            group=team.group,
        ).filter(
            home_team=team,
        ).count()

        remaining_matches += Match.objects.filter(
            tournament=self.tournament,
            stage=Match.Stage.GROUP,
            status__in=[Match.Status.SCHEDULED, Match.Status.LIVE],
        ).filter(
            group=team.group,
        ).filter(
            away_team=team,
        ).count()

        return Decimal(str(self.config["group_win"])) * Decimal(remaining_matches)

    def _future_qualification_bonus(self, team: NationalTeam) -> Decimal:
        try:
            status = team.tournament_status
        except TeamTournamentStatus.DoesNotExist:
            already_advanced = False
        else:
            already_advanced = status.advanced_from_group

        if already_advanced:
            return Decimal("0")

        return Decimal(str(self.config["qualify_knockout"]))

    def _third_place_can_still_qualify(self, team: NationalTeam, envelope) -> bool:
        # Conservative max-points rule: if the status engine has not guaranteed
        # elimination as a third-place team, keep third-place qualification alive.
        if envelope.best_third_place_points is None:
            return False

        lower_or_unknown_groups = 0
        for group, other_envelope in self.group_envelopes.items():
            if group == team.group:
                continue
            threshold = other_envelope.min_third_place_points
            if threshold is None or envelope.best_third_place_points >= threshold:
                lower_or_unknown_groups += 1

        return lower_or_unknown_groups >= 4

    def _elimination_is_possible(self, possible_positions: set[int]) -> bool:
        return bool(possible_positions & {3, 4})

    def _node_for_source_slot(self, source_slot: str) -> BracketInputNode | None:
        nodes = self.bracket_graph.nodes_for_source_slot(source_slot)
        return nodes[0] if nodes else None

    def _third_place_combo_is_fifa_valid(
        self,
        option_combo: tuple[TeamProjectionOption, ...],
    ) -> bool:
        third_options = [option for option in option_combo if option.is_third_place_option]

        if not third_options:
            return True

        if self.fifa_table is None:
            return False

        required_groups = {option.third_group for option in third_options if option.third_group}

        for qualified_groups_key, row in self.fifa_table.items():
            qualified_groups = set(qualified_groups_key)

            if not required_groups.issubset(qualified_groups):
                continue

            if all(self._third_option_matches_fifa_row(option, row) for option in third_options):
                return True

        return False

    def _third_option_matches_fifa_row(
        self,
        option: TeamProjectionOption,
        row: dict[str, str],
    ) -> bool:
        if not option.third_group or not option.source_slot:
            return False

        fifa_group_slot = f"3{option.third_group}"
        opponent_slot = _opponent_slot_for_third_group(row, fifa_group_slot)
        if opponent_slot is None:
            return False

        schedule_slot = self.third_slots_by_opponent.get(opponent_slot)
        return schedule_slot == option.source_slot


def _best_group_fantasy_points_from_position_envelope(
    team_envelope,
    *,
    position: int,
    config: dict,
) -> Decimal | None:
    """Return best fantasy points for remaining group records at position.

    Supports the enriched TeamOutcomeEnvelope introduced for projections.  If
    the current project does not yet have that enrichment, returns None and the
    caller uses an optimistic fallback.
    """
    position_envelope = None

    outcome_for_position = getattr(team_envelope, "outcome_for_position", None)
    if callable(outcome_for_position):
        position_envelope = outcome_for_position(position)
    else:
        position_outcomes = getattr(team_envelope, "position_outcomes", None) or {}
        position_envelope = position_outcomes.get(position)

    if position_envelope is None:
        return None

    # Current enriched mathematical_status.py stores the compatible remaining
    # W/D/L records here. Keep the older fallback attribute names so this
    # function remains safe across nearby development branches.
    records = getattr(position_envelope, "possible_result_records", None)
    if records is None:
        records = getattr(position_envelope, "result_records", None)
    if records is None:
        records = getattr(position_envelope, "remaining_records", None)
    if records is None:
        records = getattr(position_envelope, "records", None)

    if not records:
        return None

    return max(_group_fantasy_points_for_record(record, config) for record in records)


def _group_fantasy_points_for_record(record, config: dict) -> Decimal:
    wins = getattr(record, "wins", 0)
    draws = getattr(record, "draws", 0)
    losses = getattr(record, "losses", 0)

    if isinstance(record, tuple) and len(record) >= 3:
        wins, draws, losses = record[:3]

    return (
        Decimal(wins) * Decimal(str(config["group_win"]))
        + Decimal(draws) * Decimal(str(config["group_draw"]))
        + Decimal(losses) * Decimal(str(config["group_loss"]))
    )


def _format_knockout_event(
    event: KnockoutPathEvent,
    team_by_id: dict[int, NationalTeam],
) -> str:
    """Return a compact log line for one selected knockout path event."""
    home = _knockout_team_label(event.home_team_id, team_by_id)
    away = _knockout_team_label(event.away_team_id, team_by_id)
    winner = _knockout_team_label(event.winner_team_id, team_by_id)
    loser = _knockout_team_label(event.loser_team_id, team_by_id)
    match_label = f"M{event.match_number}" if event.match_number is not None else "M?"
    return (
        "    "
        f"{match_label} {event.stage}: "
        f"{home} vs {away} -> winner={winner}, loser={loser}; "
        f"points={event.points}"
    )


def _knockout_team_label(
    team_id: int | None,
    team_by_id: dict[int, NationalTeam],
) -> str:
    if team_id is None:
        return "non-owned"
    team = team_by_id.get(team_id)
    return team.name if team is not None else f"team_id={team_id}"


def _display_position(position: int | None, qualified: bool) -> str:
    if position is None:
        return "qualified" if qualified else "eliminated"
    return str(position)


def _dedupe_options(options: Iterable[TeamProjectionOption]) -> list[TeamProjectionOption]:
    deduped: dict[tuple, TeamProjectionOption] = {}
    for option in options:
        key = (
            option.team_id,
            option.source_position,
            option.source_slot,
            option.bracket_node_id,
            option.qualified,
        )
        current = deduped.get(key)
        if current is None or option.group_future_points > current.group_future_points:
            deduped[key] = option
    return list(deduped.values())


def _product_size(values: list[int]) -> int:
    if not values:
        return 0
    return reduce(mul, values, 1)


def _groups_for_tournament(tournament) -> list[str]:
    return list(
        NationalTeam.objects.filter(tournament=tournament)
        .exclude(group="")
        .values_list("group", flat=True)
        .distinct()
        .order_by("group")
    )


def _third_slots_by_opponent(matches: list[Match]) -> dict[str, str]:
    slots_by_opponent = {}

    for match in matches:
        home_slot = (match.home_slot or "").strip()
        away_slot = (match.away_slot or "").strip()

        if DIRECT_SLOT_RE.match(home_slot) and THIRD_PLACEHOLDER_RE.match(away_slot):
            slots_by_opponent[home_slot] = away_slot

        if DIRECT_SLOT_RE.match(away_slot) and THIRD_PLACEHOLDER_RE.match(home_slot):
            slots_by_opponent[away_slot] = home_slot

    return slots_by_opponent


def _load_fifa_table_or_none() -> dict[str, dict[str, str]] | None:
    try:
        return load_fifa_third_place_table()
    except Exception:
        return None


def _opponent_slot_for_third_group(
    fifa_row: dict[str, str],
    fifa_group_slot: str,
) -> str | None:
    for opponent_slot, value in fifa_row.items():
        if value == fifa_group_slot:
            return opponent_slot
    return None


def _actual_bracket_node_by_team(
    tournament,
    nodes: tuple[BracketInputNode, ...],
) -> dict[int, BracketInputNode]:
    node_by_team: dict[int, BracketInputNode] = {}

    for node in nodes:
        if node.resolved_team_id is None:
            continue
        node_by_team[node.resolved_team_id] = node

    return node_by_team


def _actual_knockout_slot_by_team(
    *,
    tournament,
    group_stage_complete: bool,
    third_slots_by_opponent: dict[str, str],
    fifa_table: dict[str, dict[str, str]] | None,
) -> dict[int, str]:
    slot_by_team: dict[int, str] = {}

    for match in Match.objects.filter(tournament=tournament).exclude(stage=Match.Stage.GROUP):
        if match.is_complete:
            continue

        if match.home_team_id:
            slot_by_team[match.home_team_id] = (match.home_slot or f"M{match.match_number}:home").strip()
        if match.away_team_id:
            slot_by_team[match.away_team_id] = (match.away_slot or f"M{match.match_number}:away").strip()

    if not group_stage_complete:
        return slot_by_team

    try:
        qualification = compute_qualification(tournament)
    except Exception:
        return slot_by_team

    for slot, team in qualification.slot_map.items():
        if team is not None:
            slot_by_team.setdefault(team.id, slot)

    if fifa_table is None:
        return slot_by_team

    third_group_to_team = {
        standing.team.group: standing.team
        for standing in qualification.best_third_place_teams
    }

    if len(third_group_to_team) != 8:
        return slot_by_team

    key = "".join(sorted(third_group_to_team))
    row = fifa_table.get(key)

    if not row:
        return slot_by_team

    for opponent_slot, fifa_slot in row.items():
        schedule_slot = third_slots_by_opponent.get(opponent_slot)

        if not schedule_slot or not fifa_slot:
            continue

        team = third_group_to_team.get(fifa_slot[1:])

        if team is not None:
            slot_by_team.setdefault(team.id, schedule_slot)

    return slot_by_team


def _team_is_eliminated_from_future(team: NationalTeam) -> bool:
    try:
        status = team.tournament_status
    except TeamTournamentStatus.DoesNotExist:
        return False

    if status.finish_rank is not None:
        return True

    if status.mathematically_eliminated and not status.advanced_from_group:
        return True

    return False


def _all_group_matches_complete(tournament) -> bool:
    group_matches = Match.objects.filter(tournament=tournament, stage=Match.Stage.GROUP)
    return group_matches.exists() and all(match.is_complete for match in group_matches)


def _owned_or_none(team_id: int | None, owned_team_ids: set[int]) -> int | None:
    if team_id in owned_team_ids:
        return team_id
    return None


def _actual_loser_id(match: Match) -> int | None:
    if not match.winner_id:
        return None
    if match.winner_id == match.home_team_id:
        return match.away_team_id
    return match.home_team_id


def _winner_loser_branches(
    home: int | None,
    away: int | None,
) -> list[tuple[int | None, int | None]]:
    if home is None and away is None:
        return [(None, None)]

    if home is not None and away is None:
        return [(home, None)]

    if home is None and away is not None:
        return [(away, None)]

    if home == away:
        return [(home, None)]

    return [(home, away), (away, home)]
