"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, urlparse

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    """Return a boolean from an environment variable."""

    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    """Return a comma-separated environment variable as a list."""

    value = os.getenv(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]



def env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None or value == "":
        return default
    return int(value)


def env_float(name: str, default: float) -> float:
    value = os.getenv(name)
    if value is None or value == "":
        return default
    return float(value)


def env_optional_int(name: str, default: int | None = None) -> int | None:
    value = os.getenv(name)
    if value is None or value == "":
        return default
    return int(value)

def database_from_url(url: str) -> dict:
    """Build a Django DATABASES['default'] config from DATABASE_URL.

    Supports PostgreSQL URLs such as:
    postgresql://USER:PASSWORD@HOST:PORT/DBNAME
    postgres://USER:PASSWORD@HOST:PORT/DBNAME
    """

    parsed = urlparse(url)
    scheme = parsed.scheme.lower()

    if scheme not in {"postgres", "postgresql"}:
        raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme!r}")

    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/"),
        "USER": parsed.username or "",
        "PASSWORD": parsed.password or "",
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }

    options = dict(parse_qsl(parsed.query))
    if options:
        config["OPTIONS"] = options

    return config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Railway exposes the public domain through this environment variable once a
# domain is generated for the service. Keeping this automatic avoids needing to
# hard-code the temporary Railway URL in settings.py.
RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN")
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

# Health check endpoint for platforms like Railway that require one.
ALLOWED_HOSTS.append("healthcheck.railway.app")

# Allow localhost for local development and testing.
ALLOWED_HOSTS.append('127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'leagues',
    'tournaments',
    'assignments',
    'drafts',
    'scoring',
    'live_scores',
    'channels',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Authentication redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "league_list"
LOGOUT_REDIRECT_URL = "home"

# Railway and most managed platforms terminate HTTPS before forwarding requests
# to the app. This lets Django correctly recognize secure proxied requests.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": database_from_url(DATABASE_URL),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USE_REDIS_CHANNEL_LAYER = os.getenv("USE_REDIS_CHANNEL_LAYER", "False") == "True"

if USE_REDIS_CHANNEL_LAYER:
    redis_url = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": redis_url,
                        "socket_connect_timeout": 5,
                        "socket_timeout": 30,
                        "health_check_interval": 30,
                    }
                ],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

# Background projection worker settings
PROJECTION_REDIS_URL = os.getenv("PROJECTION_REDIS_URL") or os.getenv("REDIS_URL")
PROJECTION_JOB_QUEUE = os.getenv(
    "PROJECTION_JOB_QUEUE",
    "worldcupdraft:projection_jobs",
)

# Simulation settings for the projection worker. These can be tuned to balance accuracy vs. speed.
PROJECTION_SIMULATION_RUNS = env_int("PROJECTION_SIMULATION_RUNS", 10000)
PROJECTION_SIMULATION_MODE = os.getenv("PROJECTION_SIMULATION_MODE", "seeded")
PROJECTION_SIMULATION_SEED = env_optional_int("PROJECTION_SIMULATION_SEED", 42)
PROJECTION_SIMULATION_DRAW_PROB = env_float("PROJECTION_SIMULATION_DRAW_PROB", 0.24)
PROJECTION_SIMULATION_RANK_ELO_STEP = env_float("PROJECTION_SIMULATION_RANK_ELO_STEP", 8.0)
PROJECTION_SIMULATION_REGULATION_PROB = env_float("PROJECTION_SIMULATION_REGULATION_PROB", 0.75)
PROJECTION_SIMULATION_EXTRA_TIME_PROB = env_float("PROJECTION_SIMULATION_EXTRA_TIME_PROB", 0.15)

# Live-score provider settings. The provider-neutral live_scores app uses this
# value to select the concrete API client. API-Football/API-SPORTS is currently
# the default provider because the World Cup is covered on the cheaper plans.
LIVE_SCORES_PROVIDER = os.getenv("LIVE_SCORES_PROVIDER", "api_football")

# API-Football / API-SPORTS live-score ingestion settings.
API_FOOTBALL_API_KEY = os.getenv("API_FOOTBALL_API_KEY", "") or os.getenv("API_SPORTS_API_KEY", "")
API_FOOTBALL_BASE_URL = os.getenv("API_FOOTBALL_BASE_URL", "https://v3.football.api-sports.io")
API_FOOTBALL_WORLD_CUP_LEAGUE_ID = os.getenv("API_FOOTBALL_WORLD_CUP_LEAGUE_ID", "1")
API_FOOTBALL_WORLD_CUP_SEASON = os.getenv("API_FOOTBALL_WORLD_CUP_SEASON", "2026")
API_FOOTBALL_TIMEOUT_SECONDS = env_int("API_FOOTBALL_TIMEOUT_SECONDS", 15)
API_FOOTBALL_LIVE_STATUS_CODES = os.getenv(
    "API_FOOTBALL_LIVE_STATUS_CODES",
    "1H-HT-2H-ET-BT-P-LIVE",
)

# Live-score worker defaults. The first worker slice updates LiveMatchState only;
# final Match results, standings, projections, and websocket broadcasts are handled
# by later slices. The worker uses two cadences: fast polling when a game is
# near kickoff or currently tracked as live, and slower fixture-detail checks
# during idle periods.
LIVE_SCORES_POLL_INTERVAL_SECONDS = env_int("LIVE_SCORES_POLL_INTERVAL_SECONDS", 30)
LIVE_SCORES_IDLE_SLEEP_SECONDS = env_int("LIVE_SCORES_IDLE_SLEEP_SECONDS", 300)
LIVE_SCORES_KICKOFF_BUFFER_MINUTES = env_int("LIVE_SCORES_KICKOFF_BUFFER_MINUTES", 15)
