# Generated by Django 5.2.14 on 2026-05-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='leagues.league')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='leagues.leaguemember')),
                ('national_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_assignments', to='tournaments.nationalteam')),
            ],
            options={
                'ordering': ['member__display_name', 'national_team__pot', 'national_team__name'],
                'unique_together': {('league', 'national_team')},
            },
        ),
    ]
