# Generated by Django 5.2.14 on 2026-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamassignment',
            options={'ordering': ['reveal_order', 'member__display_name', 'national_team__pot', 'national_team__name']},
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='reveal_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
