# Generated by Django 5.2.14 on 2026-05-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('draws', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('teams_advanced', models.PositiveSmallIntegerField(default=0)),
                ('best_finish_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goal_difference', models.SmallIntegerField(default=0)),
                ('goals_scored', models.PositiveSmallIntegerField(default=0)),
                ('current_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='leagues.league')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_entries', to='leagues.leaguemember')),
            ],
            options={
                'ordering': ['current_rank', '-points', 'member__display_name'],
                'unique_together': {('league', 'member')},
            },
        ),
    ]
