# Generated by Django 5.2.14 on 2026-05-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_possible_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remaining_possible_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('best_case_slots', models.JSONField(blank=True, default=dict)),
                ('is_stale', models.BooleanField(default=True)),
                ('stale_reason', models.CharField(blank=True, max_length=160)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_entries', to='leagues.league')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_entries', to='leagues.leaguemember')),
            ],
            options={
                'ordering': ['member__display_name'],
                'unique_together': {('league', 'member')},
            },
        ),
    ]
