# Generated by Django 5.2.14 on 2026-06-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_assignments_generated_at_and_more'),
        ('scoring', '0002_projectionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionJobState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_job_id', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projection_job_state', to='leagues.league')),
            ],
            options={
                'ordering': ['league__slug'],
            },
        ),
    ]
