# Generated by Django 5.2.14 on 2026-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_projectionjobstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectionjobstate',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
