# Generated by Django 5.2.14 on 2026-06-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_projectionjobstate_last_heartbeat_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionWorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(default='projection-worker', max_length=80, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_name'],
            },
        ),
    ]
