# Generated by Django 5.2.14 on 2026-06-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_projectionworkerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectionentry',
            name='simulated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectionentry',
            name='simulated_average_rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='projectionentry',
            name='simulated_average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='projectionentry',
            name='simulated_first_pick_probability',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='projectionentry',
            name='simulation_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='projectionentry',
            name='simulation_runs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
