# Generated by Django 5.2.14 on 2026-05-19 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('teams_per_manager', models.PositiveSmallIntegerField(default=4)),
                ('use_tiers', models.BooleanField(default=True)),
                ('assignment_method', models.CharField(choices=[('random', 'Random draw'), ('tiered_random', 'Tiered random draw'), ('manual', 'Commissioner assignment'), ('snake', 'Snake draft')], default='tiered_random', max_length=30)),
                ('scoring_config', models.JSONField(blank=True, default=dict)),
                ('tiebreaker_config', models.JSONField(blank=True, default=list)),
                ('sleeper_league_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioned_leagues', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leagues', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('sleeper_user_id', models.CharField(blank=True, max_length=40)),
                ('sleeper_roster_id', models.CharField(blank=True, max_length=40)),
                ('draft_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leagues.league')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'unique_together': {('league', 'display_name')},
            },
        ),
    ]
