# Generated by Django 5.2.14 on 2026-05-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguemember',
            name='draft_order',
        ),
        migrations.AlterField(
            model_name='league',
            name='assignment_method',
            field=models.CharField(choices=[('random', 'Random draw'), ('tiered_random', 'Tiered random draw')], default='tiered_random', max_length=30),
        ),
    ]
