# Generated by Django 5.2.14 on 2026-05-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_remove_leaguemember_draft_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='use_tiers',
        ),
    ]
