# Generated by Django 5.2.14 on 2026-05-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_remove_league_use_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='assignments_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='assignments_locked',
            field=models.BooleanField(default=False),
        ),
    ]
