# Generated by Django 5.2.14 on 2026-06-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0004_league_assignments_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('current_pick_index', models.PositiveIntegerField(default=0)),
                ('reveal_phase', models.CharField(choices=[('manager', 'Manager revealed'), ('team', 'Team revealed'), ('complete', 'Complete')], default='manager', max_length=20)),
                ('autoplay', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_state', to='leagues.league')),
            ],
            options={
                'ordering': ['league__name'],
            },
        ),
    ]
