# Generated by Django 5.2.14 on 2026-06-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftstate',
            name='reveal_phase',
            field=models.CharField(choices=[('buffer', 'Draft started'), ('manager', 'Manager revealed'), ('team', 'Team revealed'), ('complete', 'Complete')], default='manager', max_length=20),
        ),
    ]
